config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    post 'login', to: 'users/sessions#create', as: :login
    get 'login', to: 'users/sessions#new'
  end

  namespace :industry do
    get :jobs
    post :update_jobs
  end

  resources :market_orders, only: %i[index] do
    post :update_all, on: :collection
  end

  resources :planetary_colonies, only: %i[index] do
    post :update, on: :collection, as: :update
  end

  resources :planetary_commodities, only: %i[index show] do
    post :update_prices, on: :collection
  end

  scope '', controller: :pages do
    get :character_data
  end

  get 'settings', to: 'users#settings'
  delete 'remove_character(/:id)', to: 'users#remove_character', as: :remove_character

  root 'pages#dashboard'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :is_admin
  
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<h1>EVE Industrial tools</h1>

<h2>Spreadsheets</h2>
<ul>
  <li><%= link_to 'Ore Mining', spreadsheets_ore_mining_path %></li>
  <li><%= link_to 'Refining', spreadsheets_refining_path %></li>
  <li><%= link_to 'Ice Mining', spreadsheets_ice_mining_path %></li>
  <li><%= link_to 'Planetary Extraction', spreadsheets_planetary_extraction_path %></li>
  <li><%= link_to 'Planetary Processing', spreadsheets_planetary_processing_path %></li>
</ul>

<h2>Data</h2>
<ul>
  <li><%= link_to 'Ores', ores_path %></li>
  <li><%= link_to 'Ore Variations', variations_path %></li>
  <li><%= link_to 'Minerals', minerals_path %></li>
</ul>
<ul>
  <li><%= link_to 'Ice Ores', ice_ores_path %></li>
  <li><%= link_to 'Ice Products', ice_products_path %></li>
</ul>
<ul>
  <li><%= link_to 'Planetary Commodities', planetary_commodities_path %></li>
</ul>
<ul>
  <li><%= link_to 'Regions', regions_path %></li>
  <li><%= link_to 'Systems', systems_path %></li>
</ul>