config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    post 'login', to: 'users/sessions#create', as: :login
    get 'login', to: 'users/sessions#new'
  end

  namespace :industry do
    get :jobs
    post :update_jobs
  end

  resources :market_orders, only: %i[index] do
    post :update_all, on: :collection
  end

  resources :planetary_colonies, only: %i[index] do
    post :update, on: :collection, as: :update
  end

  resources :planetary_commodities, only: %i[index show] do
    post :update_prices, on: :collection
  end

  scope '', controller: :pages do
    get :character_data
  end

  get 'settings', to: 'users#settings'
  delete 'remove_character(/:id)', to: 'users#remove_character', as: :remove_character

  root 'pages#dashboard'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  esi_refresh_token      :string
#  esi_auth_token         :string
#  esi_expires_on         :datetime
#  character_id           :bigint
#  character_name         :string
#  character_portrait     :string
#  scopes                 :string
#  token_type             :string
#  owner_hash             :string
#  role                   :string
#  email                  :string
#  encrypted_password     :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :characters, dependent: :destroy
  has_many :industry_jobs, through: :characters
  has_many :orders, through: :characters

  def self.find_or_register(code)
    auth_response = ESI.authenticate(code)
    verification_data = ESI.verify_access_token(auth_response['access_token'])

    find_or_initialize_by(character_id: verification_data['CharacterID']).tap do |u|
      u.esi_auth_token = auth_response['access_token']
      u.esi_refresh_token = auth_response['refresh_token']
      u.verification_data = verification_data
      u.save!
    end
  end

  def self.add_character(code, user_id)
    auth_response = ESI.authenticate(code)
    verification_data = ESI.verify_access_token(auth_response['access_token'])

    Character.find_or_initialize_by(character_id: verification_data['CharacterID']).tap do |c|
      c.user_id = user_id
      c.esi_auth_token = auth_response['access_token']
      c.esi_refresh_token = auth_response['refresh_token']
      c.verification_data = verification_data
      c.save!
    end
  end

  def verification_data=(verification_data)
    self.character_name = verification_data['CharacterName']
    self.scopes = verification_data['Scopes']
    self.token_type = verification_data['TokenType']
    self.owner_hash = verification_data['CharacterOwnerHash']
    self.esi_expires_on = DateTime.parse(verification_data['ExpiresOn'])
  end

  def auth_token
    # Treat tokens as expired 5 seconds earlier
    expired_token = DateTime.now.utc + 5.seconds >= esi_expires_on
    return esi_auth_token unless expired_token

    auth_response = ESI.authenticate(esi_refresh_token, refresh: true)

    self.esi_refresh_token = auth_response['refresh_token']
    self.esi_auth_token = auth_response['access_token']
  end

  def avatar
    return character_portrait if character_portrait.present?

    portraits = ESI.fetch_character_portrait(character_id)
    update(character_portrait: portraits['px64x64'])
    character_portrait
  end

  def remember_me
    super.nil? ? true : super
  end

  def update_market_orders
    characters.each do |character|
      Order.where(character_id: character.id).delete_all
      Order.update_character_orders(character)
    end
  end

  def update_industry_jobs
    characters.each do |character|
      IndustryJob.update_character_jobs(character)
    end
  end

  def update_planetary_colonies
    characters.each do |character|
      PlanetaryColony.update_character_colonies(character)
    end
  end

  protected

  def password_required?
    false
  end

  def email_required?
    false
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :require_no_authentication, only: [:new]

  # GET /login
  def new
    return redirect_to root_path if (code = params[:code]).blank?

    do_sign_in(code) unless signed_in?

    add_character(code) if params[:state].include?('character')

    redirect_to settings_path
  end

  # POST /users/sign_in
  # def create
  #   super
  # end

  # DELETE /users/sign_out
  # def destroy
  #   super
  # end

  private

  def do_sign_in(code)
    self.resource = User.find_or_register(code)
    sign_in(resource_name, resource)
  end

  def add_character(code)
    User.add_character(code, current_user.id) if params[:state].include?('character')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def settings; end

  def remove_character
    Character.find(params[:id]).destroy
    redirect_to settings_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :login, class: 'control-label col-sm-1' %>
    <div class="col-sm-2">
      <%= f.text_field :login, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'control-label col-sm-1' %>
    <div class="col-sm-2">
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_admin, class: 'control-label col-sm-1' %>
    <div class="col-sm-2">
      <%= f.check_box :is_admin, class: 'checkbox' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-2">
      <%= f.submit class: 'btn btn-primary full-width' %>
    </div>
  </div>
  
  <% unless @user.new_record? %>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-2">
        <%= link_to 'Back', @user, class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing <%= @user.login %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<table class="table table-bordered table-striped tablesorter">
  <thead>
    <tr>
      <th>Login</th>
      <th>Last Login</th>
      <th>Register Date</th>
      <% if @can_edit %>
        <th class="edit-field">Edit</th>
      <% end %>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.login, user %></td>
        <td><%= user.last_login %></td>
        <td><%= user.created_at.to_date %></td>
        <% if @can_edit %>
          <td class="edit-field"><%= link_to image_tag('/edit.png', :alt => 'Edit'), edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_user_path, class: 'btn btn-default' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/settings.html.erb
<h1>Settings</h1>

<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h2 class="border-bottom pb-2 mb-0">Characters</h2>
  <p>User the login button to add more characters</p>
  <p><%= add_character_button %></p>
  <% current_user.characters.each do |c| %>
    <div class="d-flex text-muted pt-3">
      <%= image_tag c.avatar, class: 'character-avatar' %>

      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <h3><%= c.character_name %></h3>
          <%= button_to 'Delete', remove_character_path(c), method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.login %></h1>

<p>
  <b>Admin:</b>
  <%= @user.is_admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' if @can_edit %>
<%= link_to 'Back to List', users_path, class: 'btn btn-default' %>