config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    post 'login', to: 'users/sessions#create', as: :login
    get 'login', to: 'users/sessions#new'
  end

  namespace :industry do
    get :jobs
    post :update_jobs
  end

  resources :market_orders, only: %i[index] do
    post :update_all, on: :collection
  end

  resources :planetary_colonies, only: %i[index] do
    post :update, on: :collection, as: :update
  end

  resources :planetary_commodities, only: %i[index show] do
    post :update_prices, on: :collection
  end

  scope '', controller: :pages do
    get :character_data
  end

  get 'settings', to: 'users#settings'
  delete 'remove_character(/:id)', to: 'users#remove_character', as: :remove_character

  root 'pages#dashboard'
end

app/models/planetary_commodity.rb
# == Schema Information
#
# Table name: planetary_commodities
#
#  id           :integer          not null, primary key
#  schematic_id :integer
#  name         :string           not null
#  tier         :integer          not null
#  volume       :decimal(5, 2)
#  batch_size   :integer          not null
#  input        :text
#
class PlanetaryCommodity < ApplicationRecord
  include CSVImportable
  include MarketeerAPI

  self.primary_key = :id

  has_many :items_prices, as: :item, class_name: 'ItemsPrices', dependent: :destroy

  def isk_per_hour(factories, buy_or_sell = :buy)
    price = buy_or_sell == :buy ? buy_price : sell_price
    daily_production = batch_size * factories * cycles_per_hour
    daily_production * price
  end

  def cycles_per_hour
    tier == 1 ? 2 : 1
  end

  def self.hash_from_csv_row(row)
    {
      id: row['ID'],
      name: row['Name'],
      tier: row['Tier'],
      volume: row['Volume'],
      batch_size: row['Batch Size']
    }
  end

  def self.update_prices
    Star.pluck(:id).each do |star_id|
      update_star_prices(star_id)
    end
  end

  def self.price_list(system_id)
    fields = 'buy_price / volume AS buy_isk_per_volume, sell_price / volume AS sell_isk_per_volume'
    all.select("id, name, tier, buy_price, sell_price, #{fields}")
      .joins('JOIN items_prices ON items_prices.item_id = planetary_commodities.id')
      .where("items_prices.star_id = #{system_id}")
      .order(name: 'asc')
  end

  def self.with_price(system_id:, **query_params)
    query = all.select('id, name, tier, volume, batch_size, buy_price, sell_price, input')
      .joins('JOIN items_prices ON items_prices.item_id = planetary_commodities.id')
      .where("items_prices.star_id = #{system_id}")

    return query if query_params.empty?

    query.find_by(query_params)
  end

  private_class_method def self.update_star_prices(star_id)
    fetch_prices_for(star_id:, items: pluck(:id)).each do |item|
      item_id = item['buy']['forQuery']['types'].first
      persist_price_data(star_id, item_id, item['buy']['max'], item['sell']['max'])
    end
  end

  private_class_method def self.persist_price_data(star_id, item_id, buy_price, sell_price)
    ItemsPrices.where(star_id:, item_id:).first_or_initialize.tap do |item_price|
      item_price.item_type = name
      item_price.buy_price = buy_price
      item_price.sell_price = sell_price
      item_price.save!
    end
  end
end

app/controllers/planetary_commodities_controller.rb
class PlanetaryCommoditiesController < ApplicationController
  # GET /planetary_commodities
  # GET /planetary_commodities.json
  def index
    @planetary_commodities = PlanetaryCommodity.price_list(30_000_142)
  end

  # GET /planetary_commodities/1
  # GET /planetary_commodities/1.json
  def show
    @planetary_commodity = PlanetaryCommodity.with_price(system_id: 30_000_142, id: params[:id])
  end

  # POST /planetary_commodities/update_prices
  def update_prices
    PlanetaryCommodity.update_prices

    redirect_to planetary_commodities_path
  end
end

app/helpers/planetary_commodities_helper.rb
module PlanetaryCommoditiesHelper
end

app/views/planetary_commodities/check_central_ids.html.erb
<h1>ID Check</h1>

<table>
  <tr>
    <th>Matches</th>
    <th>Local<br/>Name</th>
    <th>EVE-Central<br/>Name</th>
  </tr>
  
  <% @results.each do |result| %>
  <tr>
    <td><%= result[:match] %></td>
    <td><%= result[:name] %></td>
    <td><%= result[:ec_name] %></td>
  </tr>
  <% end %>
</table>

app/views/planetary_commodities/edit.html.erb
<h1>Editing Planetary Commodity</h1>
<%= form_for @planetary_commodity, html: { class: 'form-horizontal' } do |f| %>
  <% if @planetary_commodity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planetary_commodity.errors.count, 'error') %> prohibited this planetary_commodity from being saved:</h2>

      <ul>
      <% @planetary_commodity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :volume, class: 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.text_field :volume, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.number_field :quantity, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tier, class: 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.number_field :tier, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :central_id, class: 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.number_field :central_id, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit class: 'btn btn-primary full-width' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= link_to 'Show', @planetary_commodity, class: 'btn btn-default ' %>
      <%= link_to 'Back', planetary_commodities_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/planetary_commodities/index.html.erb
<h1>Planetary Commodities</h1>

<%= button_to 'Update Prices', update_prices_planetary_commodities_path, class: 'btn btn-outline-primary mt-2' %>

<table class="table table-striped table-bordered mt-4" data-toggle="table">
  <thead>
    <tr>
      <th data-sortable="true" data-sorter="nameSorter">Name</th>
      <th data-sortable="true">Tier</th>
      <th data-sortable="true" data-sorter="priceSorter">ISK / Volume (buy)</th>
      <th data-sortable="true" data-sorter="priceSorter">ISK / Volume (sell)</th>
      <th data-sortable="true" data-sorter="priceSorter">Buy Price</th>
      <th data-sortable="true" data-sorter="priceSorter">Sell Price</th>
    </tr>
  </thead>

  <tbody class="table-hover">
    <% @planetary_commodities.each do |planetary_commodity| %>
      <tr>
        <td><%= link_to planetary_commodity.name, planetary_commodity %></td>
        <td><%= planetary_commodity.tier %></td>
        <td><%= number_with_delimiter(planetary_commodity.buy_isk_per_volume.round(2)) %></td>
        <td><%= number_with_delimiter(planetary_commodity.sell_isk_per_volume.round(2)) %></td>
        <td><%= number_with_delimiter(planetary_commodity[:buy_price]) %></td>
        <td><%= number_with_delimiter(planetary_commodity[:sell_price]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/planetary_commodities/show.html.erb
<div class="row text-center">
  <div class="col-sm-8 col-md-6 col-lg-4">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal"><%= @planetary_commodity.name %></h4>
      </div>
      <div class="card-body">
        <h1><%= number_with_delimiter(@planetary_commodity[:buy_price]) %> <small class="text-muted">(Buy)</small></h1>
        <h1><%= number_with_delimiter(@planetary_commodity[:sell_price]) %> <small class="text-muted">(Sell)</small></h1>
        <div class="row">
          <div class="col text-right">
            <strong>Batch Size</strong>
          </div>
          <div class="col text-left">
            <%= @planetary_commodity.batch_size %>
          </div>
        </div>
        <div class="row">
          <div class="col text-right">
            <strong>Tier</strong>
          </div>
          <div class="col text-left">
            <%= @planetary_commodity.tier %>
          </div>
        </div>
        <div class="row">
          <div class="col text-right">
            <strong>Volume</strong>
          </div>
          <div class="col text-left">
            <%= @planetary_commodity.volume %>
          </div>
        </div>
        <% if @planetary_commodity.input.present? %>
          <div class="row">
            <div class="col text-right">
              <strong>Input</strong>
            </div>
            <div class="col text-left">
              <%= @planetary_commodity.inputs %>
            </div>
          </div>
        <% end %>
        <%= link_to 'Back to List', planetary_commodities_path, class: 'btn btn-lg btn-block btn-outline-primary mt-2' %>
      </div>
    </div>
  </div>
</div>