config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    delete 'logout', to: 'users/sessions#destroy', as: :logout
    post 'login', to: 'users/sessions#create', as: :login
    get 'login', to: 'users/sessions#new'
  end

  namespace :industry do
    get :jobs
    post :update_jobs
  end

  resources :market_orders, only: %i[index] do
    post :update_all, on: :collection
  end

  resources :planetary_colonies, only: %i[index] do
    post :update, on: :collection, as: :update
  end

  resources :planetary_commodities, only: %i[index show] do
    post :update_prices, on: :collection
  end

  scope '', controller: :pages do
    get :character_data
  end

  get 'settings', to: 'users#settings'
  delete 'remove_character(/:id)', to: 'users#remove_character', as: :remove_character

  root 'pages#dashboard'
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  require 'nokogiri'
  
  skip_before_filter :is_admin
  
  def planetary_processing
    if (params.has_key? :region) && !params[:region].empty?
      items = PlanetaryCommodity.pluck :central_id
      
      # Get data from EVE-Central
      if params[:system].empty?
        prices = request_prices items, params[:region], :region
      else
        prices = request_prices items, params[:system], :system
      end
      
      # Retrieve user specific data
      taxes = { market: params[:market_tax].to_f, customs_office: params[:customs_office_tax].to_f }
      processors = { }
      processors[1] = params[:basic_processors].to_i
      processors[2] = params[:advanced_processors].to_i
      processors[3] = params[:advanced_processors].to_i
      processors[4] = params[:high_tech_processors].to_i
      
      # Save in cookies
      save_location_values
      cookies[:basic_processors] = params[:basic_processors]
      cookies[:advanced_processors] = params[:advanced_processors]
      cookies[:high_tech_processors] = params[:high_tech_processors]
      cookies[:market_tax] = params[:market_tax]
      cookies[:customs_office_tax] = params[:customs_office_tax]
      
      @refined_commodities = []
      PlanetaryCommodity.where(:tier => 2).each do |pc|
        resource = { :name => pc.name, :id => pc.id, :t0 => {}, :t1 => {} }
        resource[:t0] = pc.processing_revenue prices, taxes, processors, 0
        resource[:t1] = pc.processing_revenue prices, taxes, processors, 1
        @refined_commodities << resource
      end
      
      @specialized_commodities = []
      PlanetaryCommodity.where(:tier => 3).each do |pc|
        resource = { :name => pc.name, :id => pc.id, :t0 => {}, :t1 => {}, :t2 => {} }
        resource[:t0] = pc.processing_revenue prices, taxes, processors, 0
        resource[:t1] = pc.processing_revenue prices, taxes, processors, 1
        resource[:t2] = pc.processing_revenue prices, taxes, processors, 2
        @specialized_commodities << resource
      end
    end
    
    set_location_values
    @basic_processors = cookies[:basic_processors]
    @advanced_processors = cookies[:advanced_processors]
    @high_tech_processors = cookies[:high_tech_processors]
    @market_tax = cookies[:market_tax]
    @customs_office_tax = cookies[:customs_office_tax]
  end
  
  def planetary_extraction
    if (params.has_key? :region) && !params[:region].empty?
      items = PlanetaryCommodity.pluck :central_id
      
      # Get data from EVE-Central
      if params[:system].empty?
        prices = request_prices items, params[:region], :region
      else
        prices = request_prices items, params[:system], :system
      end
      
      # Retrieve user specific data
      taxes = { market: params[:market_tax].to_f, customs_office: params[:customs_office_tax].to_f }
      processors = { }
      processors[1] = params[:basic_processors].to_i
      processors[2] = params[:advanced_processors].to_i
      processors[3] = params[:advanced_processors].to_i
      processors[4] = params[:high_tech_processors].to_i
      
      # Save in cookies
      save_location_values
      cookies[:basic_processors] = params[:basic_processors]
      cookies[:advanced_processors] = params[:advanced_processors]
      cookies[:high_tech_processors] = params[:high_tech_processors]
      cookies[:market_tax] = params[:market_tax]
      cookies[:customs_office_tax] = params[:customs_office_tax]
      
      @materials = []
      PlanetaryCommodity.where(:tier => 1).each do |pc|
        material = { :name => pc.name, :id => pc.id }
        material[:resource] = { :name => pc.schematics[0].name, :id => pc.schematics[0].id }
        material[:revenue] = pc.extracting_revenue prices, taxes, processors
        material[:price] = prices[:buy][pc.central_id]
        @materials << material
      end
      
      @commodities = []
      PlanetaryCommodity.where(:tier => 2).each do |pc|
        resource = { :name => pc.name, :id => pc.id }
        material[:resources] = pc.requirements
        resource[:revenue] = pc.extracting_revenue prices, taxes, processors
        resource[:price] = prices[:buy][pc.central_id]
        @commodities << resource
      end
    end
    
    set_location_values
    @basic_processors = cookies[:basic_processors]
    @advanced_processors = cookies[:advanced_processors]
    @high_tech_processors = cookies[:high_tech_processors]
    @market_tax = cookies[:market_tax]
    @customs_office_tax = cookies[:customs_office_tax]
  end
  
  def refining
    if (params.has_key? :region) && !params[:region].empty?
      items = Variation.pluck(:central_id).concat(Mineral.pluck :central_id)
      
      # Retrieve user specific data
      station_yield = params[:station_yield]
      refinery_tax = params[:refinery_tax]
      market_tax = params[:market_tax]
      skills = { :special_processing_skills => {} }
      skills[:refining_skill] = params[:refining_skill]
      skills[:refinery_efficiency_skill] = params[:refinery_efficiency_skill]
      params[:processing_skills].each do |k,v|
        skill_name = '%s_processing_skill' % k
        skills[k] = v
        cookies[skill_name] = v # Also save to cookie
      end
      
      # Save in cookies
      save_location_values
      cookies[:refinery_tax] = params[:refinery_tax]
      cookies[:market_tax] = params[:market_tax]
      cookies[:station_yield] = params[:station_yield]
      cookies[:refining_skill] = params[:refining_skill]
      cookies[:refinery_efficiency_skill] = params[:refinery_efficiency_skill]
      
      # Get data from EVE-Central
      if params[:system].empty?
        prices = request_prices items, params[:region], :region
      else
        prices = request_prices items, params[:system], :system
      end
      
      @minerals = []
      Mineral.all.each do |min|
        mineral = { :id => min.id, :name => min.name }
        mineral[:price] = prices[:buy][min.central_id]
        @minerals << mineral
      end
      
      # Retrieve the information to show about each ore variation
      @variations = []
      Variation.all.each do |var|
        unless prices[:sell][var.central_id] == 0 && params[:hide_empty] 
          variation = { :id => var.id, :name => var.name }
          taxes = { refinery: refinery_tax.to_f, market: market_tax.to_f }
          refining_results = var.martket_refining prices, station_yield, skills, taxes
          variation[:price] = prices[:sell][var.central_id]
          variation[:efficiency] = refining_results[:efficiency]
          variation[:return_on_investment] = refining_results[:return_on_investment]
          @variations << variation
        end
      end
    end
    
    # Set initial values for input fields
    set_location_values
    @ores = Ore.all
    @station_yield = cookies[:station_yield]
    @refining_skill = cookies[:refining_skill]
    @refinery_efficiency_skill = cookies[:refinery_efficiency_skill]
    @refinery_tax = cookies[:refinery_tax]
    @market_tax = cookies[:market_tax]
    @processing_skills = {}
    @ores.each do |o|
      skill_name = '%s_processing_skill' % o.name
      @processing_skills[o.id] = cookies[skill_name]
    end
  end
  
  def ore_mining
    if (params.has_key? :region) && !params[:region].empty?
      items = Variation.pluck(:central_id).concat(Mineral.pluck :central_id)
      
      # Retrieve user specific data
      station_yield = params[:station_yield]
      refinery_tax = params[:refinery_tax]
      skills = { :special_processing_skills => {} }
      skills[:refining_skill] = params[:refining_skill]
      skills[:refinery_efficiency_skill] = params[:refinery_efficiency_skill]
      params[:processing_skills].each do |k,v|
        skill_name = '%s_processing_skill' % k
        skills[k] = v
        cookies[skill_name] = v # Also save to cookie
      end
      
      # Save in cookies
      save_location_values
      cookies[:refinery_tax] = params[:refinery_tax]
      cookies[:station_yield] = params[:station_yield]
      cookies[:refining_skill] = params[:refining_skill]
      cookies[:refinery_efficiency_skill] = params[:refinery_efficiency_skill]
      
      # Get data from EVE-Central
      if params[:system].empty?
        prices = request_prices items, params[:region], :region
      else
        prices = request_prices items, params[:system], :system
      end
      
      # Retrieve the information to show about each ore variation
      @variations = []
      Variation.all.each do |var|
        variation = { :id => var.id, :name => var.name }
        variation[:price] = prices[:buy][var.central_id]
        variation[:raw_revenue] = var.raw_revenue(prices[:buy][var.central_id])
        refining_results = var.refine_revenue prices[:buy], station_yield, skills, refinery_tax
        variation[:refining_revenue] = refining_results[:revenue]
        variation[:volume_reduction] = refining_results[:volume_reduction]
        variation[:refining_gain] = refining_results[:gain]
        @variations << variation
      end
    end
    
    # Set initial values for input fields
    set_location_values
    @ores = Ore.all
    @station_yield = cookies[:station_yield]
    @refining_skill = cookies[:refining_skill]
    @refinery_efficiency_skill = cookies[:refinery_efficiency_skill]
    @refinery_tax = cookies[:refinery_tax]
    @processing_skills = {}
    @ores.each do |o|
      skill_name = '%s_processing_skill' % o.name
      @processing_skills[o.id] = { }
      @processing_skills[o.id][:level] = cookies[skill_name]
      @processing_skills[o.id][:group] = o.id / 4
    end
  end
  
  def ice_mining
    if (params.has_key? :region) && !params[:region].empty?
      items = IceProduct.pluck(:central_id).concat(IceOre.pluck :central_id)
      
      # Retrieve user specific data
      station_yield = params[:station_yield]
      refinery_tax = params[:refinery_tax]
      skills = { }

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/spreadsheets/ice_mining.html.erb
<h1>Ice Spreadsheet</h1>
<% unless @ores.nil? %>
<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Ore</th>
        <th>Price / Unit<br/>(P<sub>95</sub>)</th>
        <th>Revenue / Unit<br/>Refining</th>
        <th>Refining<br/>Gain</th>
        <th>Volume<br/>Reduction</th>
      </tr>
    </thead>
    <tbody>
      <% @ores.each do |var| %>
        <tr>
          <td><%= link_to var[:name], variation_path(var[:id]) %></td>
          <% if var[:price] == 0 %>
            <td> No Buy Orders </td>
          <% else %>
            <td><%= '%.2f' % var[:price] %></td>
          <% end %>
            <td><%= '%.2f' % var[:refine_revenue] %></td>
            <% gain = var[:refining_gain] %>
            <td <%= 'class="text-warning"'.html_safe unless (gain > 0) %>><%= '%.2f %' % gain unless var[:price] == 0 %></td>
            <td><%= '%.2f %' % var[:volume] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

<%= form_tag spreadsheets_ice_mining_path do %>
  <div class="sub">
    <h2>Parameters</h2>
    <div class="form-group">
      <%= label_tag  :region %>
      <%= select_tag :region, options_from_collection_for_select(@regions, :id, :name, @region), :prompt => 'Select Region', :onchange => 'updateSystems()', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag    :system %>
      <% if @systems.nil? %>
        <%= select_tag :system, nil, :prompt => '-', class: 'form-control' %>
      <% else %>
        <%= select_tag :system, options_from_collection_for_select(@systems, :id, :name, @system), :prompt => 'Whole Region', class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag  :station_yield %>
      <%= select_tag :station_yield, options_for_select(['50','40','35','30','25'], @station_yield), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :refining_skill %>
      <%= select_tag :refining_skill, options_for_select(['0','1','2','3','4','5'], @refining_skill), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :refinery_efficiency_skill %>
      <%= select_tag :refinery_efficiency_skill, options_for_select(['0','1','2','3','4','5'], @refinery_efficiency_skill), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :ice_processing_skill %>
      <%= select_tag :ice_processing_skill, options_for_select(['0','1','2','3','4','5'], @ice_processing_skill), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :refinery_tax %>
      <%= text_field_tag :refinery_tax, @refinery_tax, :size => 3, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label>&nbsp;</label>
      <%= submit_tag 'Calculate', class: 'btn btn-default full-width' %>
    </div>
  </div>
<% end %>

app/views/spreadsheets/planetary_extraction.html.erb
<h1>Planetary Extraction Spreadsheet</h1>
<% unless @materials.nil? %>
<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Processed<br/>Material</th>
        <th>Hourly<br/>Revenue</th>
        <th>Unit<br/>Price</th>
        <th>Resource</th>
      </tr>
    </thead>
    <tbody>
      <% @materials.each do |material| %>
        <tr>
          <td><%= link_to material[:name], planetary_commodity_path(material[:id]) %></td>
          <% revenue = material[:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (revenue < 0) %>><%= revenue == 0 ? " - " : "%.2f %" % revenue %></td>
          <td><%= "%.2f" % material[:price] %></td>
          <td><%= link_to material[:name], planetary_commodity_path(material[:resource][:id]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Processed<br/>Material</th>
        <th>Hourly<br/>Revenue</th>
        <th>Unit<br/>Price</th>
        <th>Resources</th>
      </tr>
    </thead>
    <tbody>
      <% @commodities.each do |commoditiy| %>
        <tr>
          <td><%= link_to commoditiy[:name], planetary_commodity_path(commoditiy[:id]) %></td>
          <% revenue = commoditiy[:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (revenue < 0) %>><%= revenue == 0 ? " - " : "%.2f %" % revenue %></td>
          <td><%= "%.2f" % commoditiy[:price] %></td>
          <td>
            <% commodity[:resources].each_with_index do |resource, i| %>
              <% if i == commodity.requirements.size - 1 %>
                <%= link_to resource.name, resource %>
              <% else %>
                <%= link_to resource.name, resource %>, 
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

<div class="sub">
  <h2>Parameters</h2>
  <%= form_tag spreadsheets_planetary_extraction_path do %>
    <div class="form-group">
      <%= label_tag  :region %>
      <%= select_tag :region, options_from_collection_for_select(@regions, :id, :name, @region), :prompt => "Select Region", :onchange => "updateSystems()", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag    :system %>
      <% if @systems.nil? %>
        <%= select_tag :system, nil, :prompt => "-", class: "form-control" %>
      <% else %>
        <%= select_tag :system, options_from_collection_for_select(@systems, :id, :name, @system), :prompt => "Whole Region", class: "form-control" %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag  :basic_processors %>
      <%= select_tag :basic_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @basic_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :advanced_processors %>
      <%= select_tag :advanced_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @advanced_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :high_tech_processors %>
      <%= select_tag :high_tech_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @high_tech_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :market_tax %>
      <%= text_field_tag :market_tax, @market_tax, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :customs_office_tax %>
      <%= text_field_tag :customs_office_tax, @customs_office_tax, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= submit_tag "Calculate", class: "btn btn-default full-width" %>
    </div>
  <% end %>
</div>

app/views/spreadsheets/planetary_interaction.html.erb
<h1>Planetary Interaction Spreadsheet</h1>
<% unless @materials.nil? %>
<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Processed<br/>Material</th>
        <th>Hourly<br/>Revenue</th>
        <th>Resource</th>
        <th>Unit<br/>Price</th>
        <th>Return on<br/>Investment</th>
      </tr>
    </thead>
    <tbody>
      <% @materials.each do |material| %>
        <tr>
          <td><%= link_to material[:name], planetary_commodity_path(material[:id]) %></td>
          <td><%= '%d' % material[:revenue] %></td>
          <td><%= link_to material[:resource][:name], planetary_commodity_path(material[:resource][:id]) %></td>
          <td><%= '%.2f' % material[:resource][:price] %></td>
          <% revenue = material[:inversion_return] %>
          <td <%= 'class="text-warning"'.html_safe if (revenue < 0) %>><%= revenue == 0 ? ' - ' : '%.2f %' % revenue %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Processed<br/>Material</th>
        <th>Hourly<br/>Revenues</th>
        <th>Return on<br/>Investment</th>
      </tr>
    </thead>
    <tbody>
      <% @commodities.each do |commoditiy| %>
        <tr>
          <td><%= link_to commoditiy[:name], planetary_commodity_path(commoditiy[:id]) %></td>
          <td><%= '%d' % commoditiy[:revenue] %></td>
          <% revenue = commoditiy[:inversion_return] %>
          <td <%= 'class="text-warning"'.html_safe if (revenue < 0) %>><%= revenue == 0 ? ' - ' : '%.2f %' % revenue %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

<div class="sub">
  <h2>Parameters</h2>
  <%= form_tag spreadsheets_planetary_interaction_path do %>
    <div class="form-group">
      <%= label_tag  :region %>
      <%= select_tag :region, options_from_collection_for_select(@regions, :id, :name, @region), :prompt => 'Select Region', :onchange => 'updateSystems()', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag    :system %>
      <% if @systems.nil? %>
        <%= select_tag :system, nil, :prompt => '-', class: 'form-control' %>
      <% else %>
        <%= select_tag :system, options_from_collection_for_select(@systems, :id, :name, @system), :prompt => 'Whole Region', class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag  :basic_processors %>
      <%= select_tag :basic_processors, options_for_select(['0','1','2','3','4','5','6','7','8','9','10'], @basic_processors), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :advanced_processors %>
      <%= select_tag :advanced_processors, options_for_select(['0','1','2','3','4','5','6','7','8','9','10'], @advanced_processors), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :high_tech_processors %>
      <%= select_tag :high_tech_processors, options_for_select(['0','1','2','3','4','5','6','7','8','9','10'], @high_tech_processors), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :market_tax %>
      <%= text_field_tag :market_tax, @market_tax, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag  :customs_office_tax %>
      <%= text_field_tag :customs_office_tax, @customs_office_tax, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag 'Calculate', class: 'btn btn-default full-width' %>
    </div>
  <% end %>
</div>

app/views/spreadsheets/planetary_processing.html.erb
<h1>Planetary Processing Spreadsheet</h1>
<% unless @refined_commodities.nil? %>
<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Refined<br/>Commodity</th>
        <th>RoI on R0</th>
        <th>Hourly<br/>Revenue</th>
        <th>RoI on P1</th>
        <th>Hourly<br/>Revenue</th>
      </tr>
    </thead>
    <tbody>
      <% @refined_commodities.each do |commodity| %>
        <tr>
          <td><%= link_to commodity[:name], planetary_commodity_path(commodity[:id]) %></td>
          <% t0_roi = commodity[:t0][:roi] %>
          <td <%= "class=\"text-warning\"".html_safe if (t0_roi < 0) %>><%= t0_roi == 0 ? " - " : "%.2f %" % t0_roi %></td>
          <% t0_rev = commodity[:t0][:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (t0_rev < 0) %>><%= t0_rev == 0 ? " - " : "%d" % t0_rev %></td>
          <% t1_roi = commodity[:t1][:roi] %>
          <td <%= "class=\"text-warning\"".html_safe if (t1_roi < 0) %>><%= t1_roi == 0 ? " - " : "%.2f %" % t1_roi %></td>
          <% t1_rev = commodity[:t1][:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (t1_rev < 0) %>><%= t1_rev == 0 ? " - " : "%d" % t1_rev %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="sub">
  <table class="tablesorter table table-bordered table-striped">
    <thead class="pointer-cursor">
      <tr>
        <th>Specialized<br/>Commodity</th>
        <th>RoI on R0</th>
        <th>Hourly<br/>Revenue</th>
        <th>RoI on P1</th>
        <th>Hourly<br/>Revenue</th>
        <th>RoI on P2</th>
        <th>Hourly<br/>Revenue</th>
      </tr>
    </thead>
    <tbody>
      <% @specialized_commodities.each do |commodity| %>
        <tr>
          <td><%= link_to commodity[:name], planetary_commodity_path(commodity[:id]) %></td>
          <% t0_roi = commodity[:t0][:roi] %>
          <td <%= "class=\"text-warning\"".html_safe if (t0_roi < 0) %>><%= t0_roi == 0 ? " - " : "%.2f %" % t0_roi %></td>
          <% t0_rev = commodity[:t0][:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (t0_rev < 0) %>><%= t0_rev == 0 ? " - " : "%d" % t0_rev %></td>
          <% t1_roi = commodity[:t1][:roi] %>
          <td <%= "class=\"text-warning\"".html_safe if (t1_roi < 0) %>><%= t1_roi == 0 ? " - " : "%.2f %" % t1_roi %></td>
          <% t1_rev = commodity[:t1][:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (t1_rev < 0) %>><%= t1_rev == 0 ? " - " : "%d" % t1_rev %></td>
          <% t2_roi = commodity[:t2][:roi] %>
          <td <%= "class=\"text-warning\"".html_safe if (t2_roi < 0) %>><%= t2_roi == 0 ? " - " : "%.2f %" % t2_roi %></td>
          <% t2_rev = commodity[:t2][:revenue] %>
          <td <%= "class=\"text-warning\"".html_safe if (t2_rev < 0) %>><%= t2_rev == 0 ? " - " : "%d" % t2_rev %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

<div class="sub">
  <h2>Parameters</h2>
  <%= form_tag spreadsheets_planetary_processing_path do %>
    <div class="form-group">
      <%= label_tag  :region %>
      <%= select_tag :region, options_from_collection_for_select(@regions, :id, :name, @region), :prompt => "Select Region", :onchange => "updateSystems()", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag    :system %>
      <% if @systems.nil? %>
        <%= select_tag :system, nil, :prompt => "-", class: "form-control" %>
      <% else %>
        <%= select_tag :system, options_from_collection_for_select(@systems, :id, :name, @system), :prompt => "Whole Region", class: "form-control" %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag  :basic_processors %>
      <%= select_tag :basic_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @basic_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :advanced_processors %>
      <%= select_tag :advanced_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @advanced_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :high_tech_processors %>
      <%= select_tag :high_tech_processors, options_for_select(["0","1","2","3","4","5","6","7","8","9","10"], @high_tech_processors), class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :market_tax %>
      <%= text_field_tag :market_tax, @market_tax, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag  :customs_office_tax %>
      <%= text_field_tag :customs_office_tax, @customs_office_tax, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= submit_tag "Calculate", class: "btn btn-default full-width" %>
    </div>
  <% end %>
</div>